# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    paths:
      - mdp/**
    branches: [ "main" ]
  pull_request:
    paths:
      - mdp/**
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/go-build.yml
    with:
      source-path: mdp
