on:
  workflow_call:
    inputs:
      source-path:
        required: true
        type: string

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Build
      run: cd ${{inputs.source-path}}; go build -v ./...

    - name: Test
      run: cd ${{inputs.source-path}}; go test -v ./...