# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  firstProgram:
    uses: ./.github/workflows/go-build.yml
    with:
      source-path: firstProgram/wc
  interacting-todo:
    uses: ./.github/workflows/go-build.yml
    with:
      source-path: interacting/todo
  interacting-todo-cli:
    uses: ./.github/workflows/go-build.yml
    with:
      source-path: interacting/todo/cmd/todo
  mpd:
    uses: ./.github/workflows/go-build.yml
    with:
      source-path: mdp
  walk:
    uses: ./.github/workflows/go-build.yml
    with:
      source-path: walk
